### ISSUE TITLE
Fix compilation for macOS Tahoe 26.1

### ISSUE THREAD

**Issue by spacemig** [hsfl/cosmos-core#66]
### Problem
`core` fails to compile on macOS Tahoe 26.1 due to compatibility issues. This bug needs to be resolved to ensure developers using this platform can successfully build the project.

### Steps to Reproduce
1. Attempt to build `core` on macOS Tahoe 26.1
2. Observe the compiler errors and the failure to complete the build process

### Expected Behavior
- `core` should successfully compile on macOS Tahoe 26.1 without errors.

### Suggested Fix
- Investigate the root cause of the compilation errors specific to macOS Tahoe 26.1
- Apply necessary code or configuration changes to resolve build issues
- Test and verify successful compilation on the targeted OS version

### Additional Context
- Make sure to list any error messages encountered, and, if possible, provide a log or relevant code snippet showing the failure.
- Confirm successful build by running the test suite on macOS Tahoe 26.1.
